# Generated by Django 3.1.3 on 2020-11-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('zip_file', models.FileField(upload_to='game_files/', verbose_name='Архив с файлами игры')),
            ],
            options={
                'verbose_name': 'Информация о проекте',
                'verbose_name_plural': 'Информация о проекте',
            },
        ),
    ]
